In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/Algerian_forest_fires_dataset.csv")
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [ ]:
df = pd.read_csv("Algerian_forest_fires_dataset.csv")

# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

# Identify non-'Classes' columns
non_class_cols = [col for col in df.columns if col.lower() != "classes"]

# Clean and convert all non-class columns to float
for col in non_class_cols:
    df[col] = pd.to_numeric(df[col].astype(str).str.replace(r'[^\d.-]', '', regex=True), errors='coerce')

# Keep 'Classes' as-is and drop rows with NaNs in numeric columns
df = df.dropna(subset=non_class_cols)

# Save to new CSV
df.to_csv("Algerian_forest_fires_cleaned.csv", index=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    float64
 1   month        243 non-null    float64
 2   year         243 non-null    float64
 3   Temperature  243 non-null    float64
 4   RH           243 non-null    float64
 5   Ws           243 non-null    float64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    object
dtypes: float64(13), object(1)
memory usage: 28.5+ KB

In [ ]:
df.describe()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI
count,243.000000,243.000000,243.0,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000
mean,15.761317,7.502058,2012.0,32.152263,62.041152,15.493827,0.762963,77.842387,14.680658,49.430864,4.742387,16.690535,7.035391
std,8.842552,1.114793,0.0,3.628039,14.828160,2.811385,2.003207,14.349641,12.393040,47.665606,4.154234,14.228421,7.440568
min,1.000000,6.000000,2012.0,22.000000,21.000000,6.000000,0.000000,28.600000,0.700000,6.900000,0.000000,1.100000,0.000000
25%,8.000000,7.000000,2012.0,30.000000,52.500000,14.000000,0.000000,71.850000,5.800000,12.350000,1.400000,6.000000,0.700000
50%,16.000000,8.000000,2012.0,32.000000,63.000000,15.000000,0.000000,83.300000,11.300000,33.100000,3.500000,12.400000,4.200000
75%,23.000000,8.000000,2012.0,35.000000,73.500000,17.000000,0.500000,88.300000,20.800000,69.100000,7.250000,22.650000,11.450000
max,31.000000,9.000000,2012.0,42.000000,90.000000,29.000000,16.800000,96.000000,65.900000,220.400000,19.000000,68.000000,31.100000

In [ ]:
df.drop(columns = ["day", "month", "year"], inplace = True)
df.head()

   Temperature    RH    Ws  Rain  FFMC  DMC    DC  ISI  BUI  FWI      Classes
0         29.0  57.0  18.0   0.0  65.7  3.4   7.6  1.3  3.4  0.5  not fire
1         29.0  61.0  13.0   1.3  64.4  4.1   7.6  1.0  3.9  0.4  not fire
2         26.0  82.0  22.0  13.1  47.1  2.5   7.1  0.3  2.7  0.1  not fire
3         25.0  89.0  13.0   2.5  28.6  1.3   6.9  0.0  1.7  0.0  not fire
4         27.0  77.0  16.0   0.0  64.8  3.0  14.2  1.2  3.9  0.5  not fire

In [ ]:
df.isnull().sum()

Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Classes'] = label_encoder.fit_transform(df['Classes'])
df.head()

   Temperature    RH    Ws  Rain  FFMC  DMC    DC  ISI  BUI  FWI  Classes
0         29.0  57.0  18.0   0.0  65.7  3.4   7.6  1.3  3.4  0.5        5
1         29.0  61.0  13.0   1.3  64.4  4.1   7.6  1.0  3.9  0.4        5
2         26.0  82.0  22.0  13.1  47.1  2.5   7.1  0.3  2.7  0.1        5
3         25.0  89.0  13.0   2.5  28.6  1.3   6.9  0.0  1.7  0.0        5
4         27.0  77.0  16.0   0.0  64.8  3.0  14.2  1.2  3.9  0.5        5

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=["Classes"])  # Features
x

     Temperature    RH    Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI
0           29.0  57.0  18.0   0.0  65.7   3.4   7.6  1.3   3.4  0.5
1           29.0  61.0  13.0   1.3  64.4   4.1   7.6  1.0   3.9  0.4
2           26.0  82.0  22.0  13.1  47.1   2.5   7.1  0.3   2.7  0.1
3           25.0  89.0  13.0   2.5  28.6   1.3   6.9  0.0   1.7  0.0
4           27.0  77.0  16.0   0.0  64.8   3.0  14.2  1.2   3.9  0.5
..           ...   ...   ...   ...   ...   ...   ...  ...   ...  ...
242         30.0  65.0  14.0   0.0  85.4  16.0  44.5  4.5  16.9  6.5
243         28.0  87.0  15.0   4.4  41.1   6.5   8.0  0.1   6.2  0.0
244         27.0  87.0  29.0   0.5  45.9   3.5   7.9  0.4   3.4  0.2
245         24.0  54.0  18.0   0.1  79.7   4.3  15.2  1.7   5.1  0.7
246         24.0  64.0  15.0   0.2  67.3   3.8  16.5  1.2   4.8  0.5

[243 rows x 10 columns]

In [ ]:
y = df["Classes"]
y

0      5
1      5
2      5
3      5
4      5
      ..
242    2
243    5
244    5
245    5
246    6
Name: Classes, Length: 243, dtype: int64

In [ ]:
# Step 4: Split data into training and testing sets (80% train, 20% test)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# Step 6: Train the Logistic Regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
# Step 7: Make predictions
ypred = model.predict(xtest)

In [ ]:
# Step 8: Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Classification Report:\n", class_report)

Model Accuracy: 0.8979591836734694
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.89      0.96      0.93        26
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         0
           5       0.95      0.90      0.93        21

    accuracy                           0.90        49
   macro avg       0.37      0.37      0.37        49
weighted avg       0.88      0.90      0.89        49

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import joblib
joblib.dump(model, "forest_fire_model.pkl")

['forest_fire_model.pkl']

In [ ]:
from google.colab import files
files.download("forest_fire_model.pkl")